set -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

setw -g mode-keys vi

unbind r
bind C-r source-file $HOME/.tmux.conf

set -g base-index 1
set -g pane-base-index 1
bind C-v split-window -h
bind C-s split-window -v

bind -n C-M-1 select-window -t 1
bind -n C-M-2 select-window -t 1

set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -s extended-keys on

set -g window-status-format "  #I:#W  "
set -g window-status-current-format "▌ #I:#W ▐"

setw -g monitor-activity on
setw -g window-status-current-style fg=#0e0e0e,bg=#5E3A99,bold

set-option -g status-style fg=#CFC7E8,bg=#472677
set-option -g status-position top

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'

