set -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

setw -g mode-keys vi

unbind r
bind C-r source-file $HOME/.tmux.conf

bind C-v split-window -h
bind C-s split-window -v

set -g visual-activity on
set -g base-index 1
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

setw -g monitor-activity on
setw -g window-status-current-style fg=#0e0e0e,bg=#5E3A99,bold

set-option -g status-style fg=#CFC7E8,bg=#472600
set-option -g status-position top

set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'

