
# Control-X is much easier than Control+B
unbind C-b
set -g prefix C-x

# But it's even easier if we just press alt+arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind D source-file ./.tmux.dev.conf
