theme = deep
background = #131314
font-size = 15
# Feb 1st 2026 - Only available on nightly \/
# macos-option-as-alt = true
macos-icon = official
macos-titlebar-style = hidden
keybind = alt+d=scroll_page_down
keybind = alt+u=scroll_page_up
