customCommands:
  - key: "O"
    context: "files"
    description: "Open file in nvim on tmux window 1"
    command: 'pane=$(tmux list-panes -t :1 -F "#{pane_id} #{pane_current_command}" | awk "/nvim/{print \$1; exit}"); tmux send-keys -t "${pane:-:1}" Escape ":edit $(pwd)/{{.SelectedFile.Name}}" Enter'
    output: none
  - key: "O"
    context: "commitFiles"
    description: "Open file in nvim on tmux window 1"
    command: 'pane=$(tmux list-panes -t :1 -F "#{pane_id} #{pane_current_command}" | awk "/nvim/{print \$1; exit}"); tmux send-keys -t "${pane:-:1}" Escape ":edit $(pwd)/{{.SelectedCommitFile.Name}}" Enter'
    output: none
