#!/bin/bash

SESSION_NAME="session"
PROJECT_DIR="$HOME/projects/my-project"

tmux kill-session -t $SESSION_NAME 2>/dev/null
sleep 0.1

tmux new-session -d -s $SESSION_NAME -c $PROJECT_DIR -n nvim
tmux send-keys -t $SESSION_NAME:1 "nvim" C-m

tmux new-window -t $SESSION_NAME:2 -n my-server -c $PROJECT_DIR
tmux send-keys -t $SESSION_NAME:2 "iex -S mix phx.server" C-m

tmux new-window -t $SESSION_NAME:3 -n claude -c $PROJECT_DIR
tmux send-keys -t $SESSION_NAME:3 "claude" C-m

tmux new-window -t $SESSION_NAME:4 -n gh-dash -c $PROJECT_DIR
tmux send-keys -t $SESSION_NAME:4 "gh dash" C-m


tmux new-window -t $SESSION_NAME:5 -n start-up -c $PROJECT_DIR
tmux send-keys -t $SESSION_NAME:5 \
    "pg_ctl restart \
    && docker-compose up redis chrome elasticsearch -d \
    && brew services restart tailscale \
    && tailscale up \
    && exit" C-m

tmux select-window -t $SESSION_NAME:1

# Attach to session
tmux attach-session -t $SESSION_NAME

