#!/usr/bin/env bash
set -euo pipefail

current_cmd=$(tmux display-message -p '#{pane_current_command}')

if [[ "$current_cmd" =~ ^n?vim$ ]]; then
  target=$(tmux list-panes -F '#{pane_id} #{pane_current_command}' \
    | awk '$2 !~ /^n?vim$/ {print $1; exit}')
  [[ -z "$target" ]] && exit 0
  tmux select-pane -t "$target"
  tmux resize-pane -Z -t "$target"
  tmux copy-mode -t "$target"
else
  vim_pane=$(tmux list-panes -F '#{pane_id} #{pane_current_command}' \
    | awk '$2 ~ /^n?vim$/ {print $1; exit}')
  in_mode=$(tmux display-message -p '#{pane_in_mode}')
  [[ "$in_mode" == "1" ]] && tmux send-keys -X cancel
  [[ -n "$vim_pane" ]] || exit 0
  tmux resize-pane -Z
  tmux select-pane -t "$vim_pane"
fi
