-- k9s-mirror
-- Mirror Neovim's colorscheme into k9s, the way ghostty-mirror does for the
-- terminal. k9s paints its own cells from a skin file and ignores the terminal
-- palette, so changing :colorscheme leaves it on whatever skin it loaded. This
-- generates a skin from the live highlights on every ColorScheme and writes it
-- to k9s's skin dir; with `reactive: true` in k9s's config.yaml a running k9s
-- repaints the moment the file changes, so k9s flips themes alongside nvim.

local M = {}

-- macOS k9s lives under Application Support, NOT ~/.config/k9s (confirm with
-- `k9s info`). The skin filename (sans .yaml) must match `ui.skin` in config.yaml.
local skin_dir = vim.fn.expand("~/Library/Application Support/k9s/skins")
local skin_name = "ghostty-mirror"

---Convert a 24-bit color int (from nvim_get_hl) to "#rrggbb"; nil if out of range.
---@param n integer|nil
---@return string|nil
local function hex(n)
	if type(n) ~= "number" or n < 0 or n > 0xffffff then return nil end
	return string.format("#%06x", n)
end

---Resolve a highlight group to its effective attrs, following links.
---@param name string
---@return table
local function hl(name) return vim.api.nvim_get_hl(0, { name = name, link = false }) end

---fg of the first highlight group that has one, else `fallback`.
---@param groups string[]
---@param fallback string
---@return string
local function fg_of(groups, fallback)
	for _, g in ipairs(groups) do
		local c = hex(hl(g).fg)
		if c then return c end
	end
	return fallback
end

---bg of the first highlight group that has one, else `fallback`.
---@param groups string[]
---@param fallback string
---@return string
local function bg_of(groups, fallback)
	for _, g in ipairs(groups) do
		local c = hex(hl(g).bg)
		if c then return c end
	end
	return fallback
end

---Build the k9s skin YAML from the live colorscheme. Returns nil when Normal
---has no fg/bg to anchor the theme (an aborted/partial colorscheme load).
---@return string|nil
function M.generate()
	local normal = hl("Normal")
	local bg, fg = hex(normal.bg), hex(normal.fg)
	if not bg or not fg then return nil end

	-- Accent mirrors ghostty-mirror's tmux accent (Type.fg) so k9s harmonizes
	-- with the same hue the statusline uses. The rest map syntax/diagnostic
	-- groups onto k9s's semantic slots.
	local accent = fg_of({ "Type", "Function" }, fg)
	local key = fg_of({ "Function", "Keyword", "Statement" }, accent)
	local dim = fg_of({ "Comment", "NonText" }, fg)
	local border = fg_of({ "WinSeparator", "VertSplit", "Comment" }, dim)
	local sel_bg = bg_of({ "Visual" }, accent)
	local err = fg_of({ "DiagnosticError", "ErrorMsg" }, "#ff5f5f")
	local warn = fg_of({ "DiagnosticWarn", "WarningMsg" }, "#ffaf00")
	local add = fg_of({ "DiagnosticOk", "diffAdded", "Added", "String" }, "#5fff5f")
	local modify = fg_of({ "DiagnosticInfo", "diffChanged", "Changed" }, accent)
	local value = fg_of({ "String", "Constant", "Number" }, fg)

	-- Hand-rolled YAML: a flat, fixed-shape document, so concatenation is clearer
	-- than pulling in a serializer. Anchors keep it close to k9s's stock skins.
	return ([[
# Generated by k9s-mirror (nvim) — mirrors the active Neovim colorscheme.
# Do not edit by hand; :colorscheme rewrites this file.
k9s:
  body:
    fgColor: &fg "%s"
    bgColor: &bg "%s"
    logoColor: "%s"
    logoColorMsg: "%s"
  prompt:
    fgColor: *fg
    bgColor: *bg
    suggestColor: "%s"
  info:
    fgColor: "%s"
    sectionColor: *fg
  dialog:
    fgColor: *fg
    bgColor: *bg
    buttonFgColor: *bg
    buttonBgColor: "%s"
    buttonFocusFgColor: *bg
    buttonFocusBgColor: "%s"
    labelFgColor: "%s"
    fieldFgColor: *fg
  frame:
    border:
      fgColor: "%s"
      focusColor: "%s"
    menu:
      fgColor: *fg
      keyColor: "%s"
      numKeyColor: "%s"
    crumbs:
      fgColor: *bg
      bgColor: "%s"
      activeColor: "%s"
    status:
      newColor: "%s"
      modifyColor: "%s"
      addColor: "%s"
      errorColor: "%s"
      highlightColor: "%s"
      killColor: "%s"
      completedColor: "%s"
    title:
      fgColor: "%s"
      bgColor: *bg
      highlightColor: "%s"
      counterColor: "%s"
      filterColor: "%s"
  views:
    charts:
      bgColor: *bg
      defaultDialColors: ["%s", "%s"]
      defaultChartColors: ["%s", "%s"]
    table:
      fgColor: *fg
      bgColor: *bg
      cursorFgColor: *bg
      cursorBgColor: "%s"
      header:
        fgColor: *fg
        bgColor: *bg
        sorterColor: "%s"
    xray:
      fgColor: *fg
      bgColor: *bg
      cursorColor: "%s"
      graphicColor: "%s"
    yaml:
      keyColor: "%s"
      colonColor: "%s"
      valueColor: "%s"
    logs:
      fgColor: *fg
      bgColor: *bg
      indicator:
        fgColor: *bg
        bgColor: "%s"
]]):format(
		fg,
		bg,
		accent, -- logoColor
		key, -- logoColorMsg
		dim, -- prompt.suggestColor
		accent, -- info.fgColor
		accent, -- dialog.buttonBgColor
		key, -- dialog.buttonFocusBgColor
		accent, -- dialog.labelFgColor
		border, -- frame.border.fgColor
		accent, -- frame.border.focusColor
		key, -- menu.keyColor
		accent, -- menu.numKeyColor
		accent, -- crumbs.bgColor
		key, -- crumbs.activeColor
		add, -- status.newColor
		modify, -- status.modifyColor
		add, -- status.addColor
		err, -- status.errorColor
		accent, -- status.highlightColor
		err, -- status.killColor
		dim, -- status.completedColor
		accent, -- title.fgColor
		key, -- title.highlightColor
		warn, -- title.counterColor
		add, -- title.filterColor
		accent, -- charts.defaultDialColors[0]
		err, -- charts.defaultDialColors[1]
		accent, -- charts.defaultChartColors[0]
		err, -- charts.defaultChartColors[1]
		sel_bg, -- table.cursorBgColor
		accent, -- table.header.sorterColor
		accent, -- xray.cursorColor
		key, -- xray.graphicColor
		key, -- yaml.keyColor
		dim, -- yaml.colonColor
		value, -- yaml.valueColor
		accent -- logs.indicator.bgColor
	)
end

---Generate the skin and write it to k9s's skin dir. No-op when generation
---isn't possible. Fails silently — a broken k9s skin must never break nvim.
function M.write()
	local lines = M.generate()
	if not lines then return end
	vim.fn.mkdir(skin_dir, "p")
	-- writefile is fine here: k9s polls the file (reactive), and a torn read just
	-- gets corrected on the next ColorScheme. No cross-process atomicity needed.
	pcall(vim.fn.writefile, vim.split(lines, "\n"), skin_dir .. "/" .. skin_name .. ".yaml")
end

-- Coalesce a colorscheme picker's live preview (one ColorScheme per previewed
-- scheme) so we only write once the scheme settles.
local timer
local function schedule()
	if timer then
		timer:stop()
		timer:close()
	end
	timer = vim.uv.new_timer()
	local t = timer
	t:start(
		150,
		0,
		vim.schedule_wrap(function()
			if t:is_closing() then return end
			t:close()
			if timer == t then timer = nil end
			M.write()
		end)
	)
end

function M.setup()
	local group = vim.api.nvim_create_augroup("k9s-mirror", { clear = true })
	vim.api.nvim_create_autocmd("ColorScheme", { group = group, callback = schedule })
	vim.api.nvim_create_user_command("K9sMirror", M.write, {
		desc = "Regenerate the k9s skin from the current colorscheme",
	})
	-- setup may run after the startup colorscheme already loaded (no further
	-- ColorScheme event), so write once now if a scheme is live.
	if hl("Normal").bg then M.write() end
end

return M
